using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace DebtChecking.Facilities
{
    public partial class LandingPageRequestSLIK : DataPage
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            string urlLogin = DebtChecking.CommonForm.CustomFunction.CheckSession();
            if (string.IsNullOrEmpty(urlLogin))
            {
                if (Request.QueryString["requestid"] != null)
                {
                    string reqid = Request.QueryString["requestid"];
                    if (reqid != "" && reqid != "(autogenerated)")
                    {
                        if (reqid.ToLower().EndsWith("bu"))
                        {
                            Response.Redirect("../ScreenMenu.aspx?sm=BIC|REQ|BU&passurl&mntitle=Input Request SLIK checking&mode=edit&requestid=" + reqid);
                        }
                        else if (reqid.ToLower().EndsWith("i"))
                        {
                            Response.Redirect("../ScreenMenu.aspx?sm=BIC|REQ|I&passurl&mntitle=Input Request SLIK checking&mode=edit&requestid=" + reqid);
                        }
                    }
                }
            }
            else
            {
                Response.Redirect(urlLogin);
            }
        }

        protected void INDIVIDU_Click(object sender, EventArgs e)
        {
            GoToPage("IND");
        }


        protected void PERUSAHAAN_Click(object sender, EventArgs e)
        {
            GoToPage("PSH");
        }
        private void GoToPage(string v)
        {
            if (v == "PSH")
            {
                Response.Redirect("../ScreenMenu.aspx?sm=BIC|REQ|BU&passurl&mntitle=Input Request SLIK checking&mode=new&requestid=" + genreqid(v));
            }
            else
            {
                Response.Redirect("../ScreenMenu.aspx?sm=BIC|REQ|I&passurl&mntitle=Input Request SLIK checking&mode=new&requestid=" + genreqid(v));
            }
        }
        private string genreqid(string cust_type)
        {
            string reqid = "";
            object[] param = new object[] { cust_type };
            conn.ExecReader("exec sp_gen_requestid @1", param, dbtimeout);
            if (conn.hasRow()) reqid = conn.GetFieldValue(0);
            return reqid;
        }

    }
}